default:
  BackendApiHost: localhost
  BackendApiPort: 3000
  Geofences: [
    {
      name: 'Воронеж',
      # array of [latitude, longitude] coordinates
      polygon: []
    },
    {
      name: 'Град',
      polygon: []
    }]

development:

production: &production
  BackendApiHost: www.instacab.ru
  BackendApiPort: 80

staging:
    <<: *production
